# name: Deploy Flutter Web

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write

#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.27.0"
#           channel: "stable"

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Enable Flutter web
#         run: flutter config --enable-web

#       - name: Build web
#         run: flutter build web --release --base-href /portfolio/

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.GH_TOKEN }}
#           publish_dir: ./build/web
#           force_orphan: true
#           user_name: "github-actions[bot]"
#           user_email: "github-actions[bot]@users.noreply.github.com"
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is important for the deployment action

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Using v3 for better compatibility

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Build the Flutter web app
        run: flutter build web --release --base-href /portfolio/

      # Create .nojekyll file to prevent Jekyll processing
      - name: Add .nojekyll file
        run: touch build/web/.nojekyll

      # Deploy to GitHub Pages using a dedicated action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files from the deployment branch
