# name: Deploy Flutter Web

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write

#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.27.0"
#           channel: "stable"

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Enable Flutter web
#         run: flutter config --enable-web

#       - name: Build web
#         run: flutter build web --release --base-href /portfolio/

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.GH_TOKEN }}
#           publish_dir: ./build/web
#           force_orphan: true
#           user_name: "github-actions[bot]"
#           user_email: "github-actions[bot]@users.noreply.github.com"
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Enable Flutter web
        run: |
          flutter config --enable-web

      - name: Build the Flutter web app
        run: |
          flutter build web --release --base-href /portfolio/
          

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd build/web
          git init
          git config --global user.name 'nehatanwardev'
          git config --global user.email 'nehatanwar.dev@gmail.com'
          git add .
          git commit -m "Deploy Flutter web app to GitHub Pages"
          git branch -M gh-pages
          git remote add origin https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages
